name: CloudSim CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify initial structure
      run: |
        echo "Working Directory: $PWD"
        echo "Top-level Files:"
        ls -la
        echo "Looking for CostOptimizationSimulation.java"
        find . -name "CostOptimizationSimulation.java" || echo "File not found"
    
    - name: Set up Java 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: maven

    - name: Ensure Maven structure and move source file
      run: |
        mkdir -p src/main/java/cloudsim/simulations
        
        if [ -f "CostOptimizationSimulation.java" ]; then
          mv CostOptimizationSimulation.java src/main/java/cloudsim/simulations/
        elif [ -f "src/cloudsim/simulations/CostOptimizationSimulation.java" ]; then
          mv src/cloudsim/simulations/CostOptimizationSimulation.java src/main/java/cloudsim/simulations/
        fi
        
        echo "Updated Java Source Structure:"
        find src/main/java

    - name: Check for pom.xml
      run: |
        if [ ! -f "pom.xml" ]; then
          echo "ERROR: pom.xml not found in the root directory!"
          exit 1
        fi

    - name: Build with Maven
      run: mvn clean compile

    - name: Run simulation
      run: |
        echo "Checking class output:"
        ls -la target/classes/cloudsim/simulations/ || echo "No compiled classes"

        echo "Running Java Simulation..."
        java -cp "target/classes:target/dependency/*" cloudsim.simulations.CostOptimizationSimulation

    - name: Archive build and reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: simulation-output
        path: |
          target/classes/
          target/surefire-reports/
