name: CloudSim CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated from v3 to v4

    - name: Set up Java 8
      uses: actions/setup-java@v4  # Updated from v3 to v4
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: maven

    - name: Verify structure and move files
      run: |
        mkdir -p src/main/java/cloudsim/simulations
        if [ -f "CostOptimizationSimulation.java" ]; then
          mv CostOptimizationSimulation.java src/main/java/cloudsim/simulations/
        fi

    - name: Build with Maven
      run: mvn clean compile

    - name: Run simulation
      run: |
        java -cp "target/classes:lib/*" cloudsim.simulations.CostOptimizationSimulation

    - name: Archive results
      if: always()
      uses: actions/upload-artifact@v4  # Updated from v3 to v4
      with:
        name: simulation-results
        path: |
          target/classes/
          target/surefire-reports/