name: CloudSim CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'

    - name: Verify directory structure
      run: |
        echo "Working Directory: $PWD"
        ls -R

    - name: Build project with Maven
      run: |
        mvn clean compile

    - name: Run simulation
      run: |
        echo "Copying dependencies..."
        mvn dependency:copy-dependencies
        echo "Running simulation..."
        java -cp "target/classes:target/dependency/*:lib/*" cloudsim.simulations.CostOptimizationSimulation

    - name: Archive simulation results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: simulation-output
        path: |
          target/classes/
          target/surefire-reports/
