name: CloudSim CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4
    
    - name: Set up Java 8
      uses: actions/setup-java@v4  # Updated to v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Verify project structure
      run: |
        echo "Current directory structure:"
        ls -la
        echo "Source files:"
        find src -type f
        echo "Library files:"
        ls -la lib/
        
    - name: Prepare Maven structure
      run: |
        mkdir -p src/main/java/cloudsim/simulations
        # Move source file if it exists in non-standard location
        [ -f "src/cloudsim/simulations/CostOptimizationSimulation.java" ] && \
          mv "src/cloudsim/simulations/CostOptimizationSimulation.java" "src/main/java/cloudsim/simulations/"
        
    - name: Build with Maven
      run: mvn -B clean compile  # -B for batch mode
      
    - name: Run CloudSim
      run: java -cp "target/classes:lib/*" cloudsim.simulations.CostOptimizationSimulation
      
    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: cloudsim-results
        path: |
          target/classes/
          target/surefire-reports/
        retention-days: 3
